export interface Invoicecancelgrid{
    invoice_Id: number,
    invoice_Number: string,
    invoice_Date: string,
    irN_Status: string,
    Company_Id: number,
    company_Code: string,
    Cost_Center_Mapping_Id: number,
    map_Name: string,
    Pay_Period_Id: number,
    pay_Period: string,
    Invoice_Type_Id: number,
    InvoiceType: string,
    StateId: number,
    State_Name: string,
    amount:number,
    net_Amount: number,
    Status: string,
    IRN_Number: string,
    cgsT_Amount: number,
    sgsT_Amount: number,
    igsT_Amount: number,
    cancelledOn:string,
    creditNoteNumber:string,
    creditNote_Status:string,
    crn_IRN_Status: string,
    crn_IRN_Number:string,
    remarks:string,
    reRaiseInvoice:string
}